### ISSUE TITLE
`npx sonarwhal` doesn't work

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1021]
Running `npx sonarwhal example.com` results in:

```
info looking for local prebuild @ prebuilds/iltorb-v2.3.0-node-v57-darwin-x64.tar.gz
info looking for cached prebuild @ /Users/xxxxx/.npm/_prebuilds/https-github.com-MayhemYDG-iltorb-releases-download-v2.3.0-iltorb-v2.3.0-node-v57-darwin-x64.tar.gz
info found cached prebuild 
info unpacking @ /Users/xxxxx/.npm/_prebuilds/https-github.com-MayhemYDG-iltorb-releases-download-v2.3.0-iltorb-v2.3.0-node-v57-darwin-x64.tar.gz
info unpack resolved to /Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/node_modules/iltorb/build/bindings/iltorb.node
info unpack required /Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/node_modules/iltorb/build/bindings/iltorb.node successfully
info install Successfully installed iltorb binary!
Couldn't find a valid path to load the configuration file.
? A valid configuration file can't be found. Do you want to create a new one? Yes
Welcome to sonarwhal configuration generator
? Do you want to use a predefined configuration or create your own based on your installed pa
ckages? predefined
? Choose the configuration you want to extend from web-recommended
Installing packages...
✔ Running command: npm install @sonarwhal/configuration-web-recommended -g
Configuration file .sonarwhalrc was created.
Error: Resource web-recommended not found
    at Object.exports.loadResource (/Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadConfiguration (/Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:208:20)
    at userConfig.extends.map (/Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/dist/src/lib/config.js:38:52)
    at Array.map (<anonymous>)
    at composeConfig (/Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/dist/src/lib/config.js:37:47)
    at Function.fromConfig (/Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/dist/src/lib/config.js:149:28)
    at exports.analyze (/Users/xxxxx/.npm/_npx/2213/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:111:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

---

Thanks for @sota1235 for catching this!

**Comment by molant** [comment]
I think the solution would be to run `npm install @sonarwhal/configuration-web-recommended` without the global option in this scenario but I have no idea on how to test this :/

**Comment by molant** [comment]
I couldn't repro this anymore with the beta package of webhint (`npx hint https://example.com`) so closing.
