### ISSUE TITLE
downloadedUnhandled rejection promise: window.requestAnimationFrame is not a function

### ISSUE THREAD

**Issue by pparmentier** [webhintio/hint#1144]
Please tell us about your:

## Environment

* __`sonarwhal`__ version = 1.11.2
* __`Node.js`__ version = v8.9.4
* __`npm`__ version = 6.1.0

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js

{
    "extends": ["web-recommended"],
}

```

</details>

## URL for which `sonarwhal` failed

* https://chanel.com/us

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text

- https://www.chanel.com/ … e-onechanel/onechanel.js downloadedUnhandled rejection promise:
    uri: undefined
    message: window.requestAnimationFrame is not a function
    stack:
TypeError: window.requestAnimationFrame is not a function
    at https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:11025
    at new Promise (<anonymous>)
    at e.value (https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:10994)
    at https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:13141
    at https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:40915
    at Array.forEach (<anonymous>)
    at s.trigger (https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:40895)
    at s.show (https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:40468)
    at e.value (https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:12433)
    at https://www.chanel.com/_ui/responsive/theme-onechanel/onechanel.js:1:13784

```

</details>

**Comment by molant** [comment]
Similar to #521. We should be capable of fixing it once we have #163 (which we should be capable of doing in the next release of jsdom)

**Comment by molant** [comment]
Closing in favor of #1223
