### ISSUE TITLE
Cannot analyse a website using https://webhint.io

### ISSUE THREAD

**Issue by meziantou** [webhintio/hint#1222]
Please tell us about your:

## Environment

Online: https://webhint.io/

## `webhint` configuration

<details>
<summary>configuration</summary>

````json
[
   {
      "hintsTimeout":120000,
      "parsers":[
         "manifest"
      ],
      "hints":{
         "apple-touch-icons":"warning",
         "content-type":"error",
         "disown-opener":"error",
         "highest-available-document-mode":"error",
         "http-cache":"error",
         "http-compression":[
            "error",
            {
               "html":{
                  "zopfli":false,
                  "brotli":false
               }
            }
         ],
         "manifest-app-name":"warning",
         "manifest-exists":"off",
         "manifest-file-extension":"warning",
         "manifest-is-valid":"error",
         "meta-charset-utf-8":"error",
         "meta-viewport":"error",
         "minified-js":"error",
         "no-bom":"error",
         "no-broken-links":"off",
         "no-disallowed-headers":[
            "error",
            {
               "ignore":[
                  "Server"
               ]
            }
         ],
         "no-friendly-error-pages":"warning",
         "no-html-only-headers":"error",
         "no-http-redirects":[
            "error",
            {
               "max-target-redirects":1
            }
         ],
         "no-p3p":"off",
         "no-protocol-relative-urls":"error",
         "performance-budget":[
            "error",
            {
               "connectionType":"4G",
               "loadTime":5
            }
         ],
         "sri":"error",
         "strict-transport-security":"error",
         "validate-set-cookie-header":"error",
         "x-content-type-options":"error"
      },
      "formatters":"summary",
      "connector":{
         "options":{
            "waitFor":5000
         },
         "name":"jsdom"
      },
      "browserslist":[
         "> 1%",
         "last 1 version"
      ],
      "ignoredUrls":[
         {
            "domain":"^https?://cdn\\.jsdelivr\\.net/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://.*\\.google-analytics\\.com/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://fonts\\.googleapis\\.com/.*",
            "hints":[
               "*"
            ]
         }
      ]
   },
   {
      "hintsTimeout":120000,
      "parsers":[
         "manifest"
      ],
      "hints":{
         "html-checker":"off",
         "image-optimization-cloudinary":[
            "error",
            {
               "threshold":5
            }
         ],
         "no-vulnerable-javascript-libraries":"error"
      },
      "formatters":"summary",
      "connector":{
         "options":{
            "waitFor":5000
         },
         "name":"jsdom"
      },
      "browserslist":[
         "> 1%",
         "last 1 version"
      ],
      "ignoredUrls":[
         {
            "domain":"^https?://cdn\\.jsdelivr\\.net/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://.*\\.google-analytics\\.com/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://fonts\\.googleapis\\.com/.*",
            "hints":[
               "*"
            ]
         }
      ]
   },
   {
      "hintsTimeout":120000,
      "parsers":[
         "manifest"
      ],
      "hints":{
         "axe":"error"
      },
      "formatters":"summary",
      "connector":{
         "options":{
            "waitFor":5000
         },
         "name":"jsdom"
      },
      "browserslist":[
         "> 1%",
         "last 1 version"
      ],
      "ignoredUrls":[
         {
            "domain":"^https?://cdn\\.jsdelivr\\.net/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://.*\\.google-analytics\\.com/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://fonts\\.googleapis\\.com/.*",
            "hints":[
               "*"
            ]
         }
      ]
   },
   {
      "hintsTimeout":170000,
      "parsers":[
         "manifest"
      ],
      "hints":{
         "ssllabs":"error"
      },
      "formatters":"summary",
      "connector":{
         "options":{
            "waitFor":1000
         },
         "name":"jsdom"
      },
      "browserslist":[
         "> 1%",
         "last 1 version"
      ],
      "ignoredUrls":[
         {
            "domain":"^https?://cdn\\.jsdelivr\\.net/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://.*\\.google-analytics\\.com/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://fonts\\.googleapis\\.com/.*",
            "hints":[
               "*"
            ]
         }
      ]
   },
   {
      "hintsTimeout":170000,
      "parsers":[
         "manifest"
      ],
      "hints":{
         "stylesheet-limits":"error"
      },
      "formatters":"summary",
      "connector":{
         "options":{
            "waitFor":1000
         },
         "name":"jsdom"
      },
      "browserslist":[
         "> 1%",
         "last 1 version"
      ],
      "ignoredUrls":[
         {
            "domain":"^https?://cdn\\.jsdelivr\\.net/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://.*\\.google-analytics\\.com/.*",
            "hints":[
               "*"
            ]
         },
         {
            "domain":"^https?://fonts\\.googleapis\\.com/.*",
            "hints":[
               "*"
            ]
         }
      ]
   }
]
````

</details>

## URL for which `webhint` failed

* https://www.meziantou.net (Permalink: https://webhint.io/scanner/bf8e4a4f-aee2-4726-99e1-ac796c407672)

## Output

<details>
<summary>webhint’s raw output</summary>

All rules output:
```text
Error in webhint analyzing this hint
```

</details>

**Comment by alrra** [comment]
@meziantou Thanks for opening this issue!

Can you try to run `npx hint http://www.meziantou.net`, and if it that fails, `npx hint http://www.meziantou.net --debug` and post the output of that here? Thanks!

**Comment by alrra** [comment]
```bash
 hint:utils:appinsights Sending exception to Application Insights: Error: EPERM: operation not permitted, unlink 'C:\Users\mezia\AppData\Roaming\npm-cache\_npx\1276\node_modules\hint\node_modules\canvas-prebuilt\canvas\build\Release\canvas.node' +51s
  hint:utils:appinsights Sending pending data to Application Insights +8ms
Unhandled rejection promise:
```

@sarvaje When you have time, can you take a look? Thanks!

**Comment by alrra** [comment]
@meziantou Thank you for providing the debug information!

**Comment by sarvaje** [comment]
I get this error:

```
Analyzing https://www.meziantou.net/Unhandled rejection promise:
    uri: undefined
    message: write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:802:

    stack:
Error: write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:802:

    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\github\hint\node_modules\zone.js\dist\zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\github\hint\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

**Comment by sarvaje** [comment]
This is working now online and in the cli. https://webhint.io/scanner/e103f894-0f13-483d-bbdf-d3ad99359dfa.
