### ISSUE TITLE
Unable to use webhint with edge connector (package is not avaialable in npm)

### ISSUE THREAD

**Issue by IllusionMH** [webhintio/hint#1237]
Full output log can be found in relevant section.

**TL;DR:** Webhint tries to install missing package for edge connector from npm using `@hint/connector-edge@latest` (name created [here](https://github.com/webhintio/hint/blob/53bccffe498c9947654fe4581f1d6cdb02db1890/packages/hint/src/lib/cli/analyze.ts#L308)) and fails with 404 error.

As I can see - there were no (public) release of such package: [@hint/connector-edge](https://www.npmjs.com/package/@hint/connector-edge) (opens NPM login page)

Other connectors can be found in npm with new namespase: [@hint/connector-chrome](https://www.npmjs.com/package/@hint/connector-chrome) and [@hint/connector-jsdom](https://www.npmjs.com/package/@hint/connector-jsdom)

And I can find `connector-edge` package in old namespace [@sonarwhal/connector-edge](https://www.npmjs.com/package/@sonarwhal/connector-edge)

**Other question:** Is it possible that there are more packages that were not released (to public) with new namespace `@hint` ?
**UPD:** Looks like `connector-edge` is the only package that was released in `@sonarwhal` namespace, but wasn't in `@hint` namespace.

Please tell us about your:

## Environment

* __`hint` version:__ 3.1.0 (global installation)
* __`Node.js` version:__ 9.11.0
* __`npm` version:__ 5.6.0

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

`.hintrc` in `CWD`
```js
{
    "connector": "edge",
    "formatters": ["json"],
    "extends": ["web-recommended"]
}
```

</details>

## URL for which `webhint` failed

* __URL:__ https://example.com

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
$ hint --debug https://example.com
  hint:utils:appinsights Application Insight disabled +0ms
  hint:utils:network:as-uri Adding valid target: https://example.com/ +0ms
  hint:cli:analyze Loading configuration file from C:\web\.hintrc. +0ms
  hint:config:config-validator Validating configuration +0ms
  hint:config Composing configuration from extends +0ms
  hint:utils:resource-loader Searching web-recommended… +0ms
  hint:utils:resource-loader @hint/configuration-web-recommended is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader web-recommended found in @hint/configuration-web-recommended +2ms
  hint:config:config-validator Validating configuration +18ms
  hint:config Composing configuration from extends +5ms
  hint:config overriding config settings with values provided via CLI +1ms
  hint:config Initializing ignored urls +5ms
  hint:utils:resource-loader Searching edge… +8ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +17ms
  hint:utils:resource-loader @hint/connector-edge is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader Can't require @hint/connector-edge +0ms
  hint:utils:resource-loader hint-connector-edge is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader Can't require hint-connector-edge +0ms
  hint:utils:resource-loader C:\web\nvm\v9.11.0\node_modules\hint\dist\src\lib\connectors\edge\edge.js is not a JSON file, trying to load it
normally +1ms
  hint:utils:resource-loader Can't require C:\web\nvm\v9.11.0\node_modules\hint\dist\src\lib\connectors\edge\edge.js +1ms
  hint:utils:resource-loader C:\web is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader Can't require C:\web +1ms
  hint:utils:resource-loader Resource edge not found +0ms
  hint:utils:resource-loader ResourceError: Resource edge not found
  hint:utils:resource-loader     at Object.exports.loadResource (C:\web\nvm\v9.11.0\node_modules\hint\dist\src\lib\utils\resource-loader.js:245:15)
  hint:utils:resource-loader     at Object.exports.loadResources (C:\web\nvm\v9.11.0\node_modules\hint\dist\src\lib\utils\resource-loader.js:292:29)
  hint:utils:resource-loader     at exports.default (C:\web\nvm\v9.11.0\node_modules\hint\dist\src\lib\cli\analyze.js:196:36)
  hint:utils:resource-loader     at <anonymous>
  hint:utils:resource-loader     at process._tickCallback (internal/process/next_tick.js:182:7)
  hint:utils:resource-loader     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
  hint:utils:resource-loader     at startup (internal/bootstrap/node.js:201:19)
  hint:utils:resource-loader     at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3) +1ms
  hint:utils:resource-loader Searching axe… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +3ms
  hint:utils:resource-loader @hint/hint-axe is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader axe found in @hint/hint-axe +15ms
  hint:utils:resource-loader Searching content-type… +2ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +2ms
  hint:utils:resource-loader @hint/hint-content-type is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader content-type found in @hint/hint-content-type +21ms
  hint:utils:resource-loader Searching disown-opener… +2ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +2ms
  hint:utils:resource-loader @hint/hint-disown-opener is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader disown-opener found in @hint/hint-disown-opener +252ms
  hint:utils:resource-loader Searching highest-available-document-mode… +3ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-highest-available-document-mode is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader highest-available-document-mode found in @hint/hint-highest-available-document-mode +0ms
  hint:utils:resource-loader Searching html-checker… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +7ms
  hint:utils:resource-loader @hint/hint-html-checker is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader html-checker found in @hint/hint-html-checker +3ms
  hint:utils:resource-loader Searching http-cache… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-http-cache is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader http-cache found in @hint/hint-http-cache +7ms
  hint:utils:resource-loader Searching http-compression… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-http-compression is not a JSON file, trying to load it normally +4ms
  hint:utils:resource-loader http-compression found in @hint/hint-http-compression +42ms
  hint:utils:resource-loader Searching meta-charset-utf-8… +2ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +2ms
  hint:utils:resource-loader @hint/hint-meta-charset-utf-8 is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader meta-charset-utf-8 found in @hint/hint-meta-charset-utf-8 +180ms
  hint:utils:resource-loader Searching meta-viewport… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +3ms
  hint:utils:resource-loader @hint/hint-meta-viewport is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader meta-viewport found in @hint/hint-meta-viewport +0ms
  hint:utils:resource-loader Searching no-bom… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +6ms
  hint:utils:resource-loader @hint/hint-no-bom is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader no-bom found in @hint/hint-no-bom +0ms
  hint:utils:resource-loader Searching no-disallowed-headers… +4ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-no-disallowed-headers is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader no-disallowed-headers found in @hint/hint-no-disallowed-headers +7ms
  hint:utils:resource-loader Searching no-friendly-error-pages… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +3ms
  hint:utils:resource-loader @hint/hint-no-friendly-error-pages is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader no-friendly-error-pages found in @hint/hint-no-friendly-error-pages +0ms
  hint:utils:resource-loader Searching no-html-only-headers… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-no-html-only-headers is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader no-html-only-headers found in @hint/hint-no-html-only-headers +7ms
  hint:utils:resource-loader Searching no-http-redirects… +4ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +3ms
  hint:utils:resource-loader @hint/hint-no-http-redirects is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader no-http-redirects found in @hint/hint-no-http-redirects +2ms
  hint:utils:resource-loader Searching no-protocol-relative-urls… +2ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +2ms
  hint:utils:resource-loader @hint/hint-no-protocol-relative-urls is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader no-protocol-relative-urls found in @hint/hint-no-protocol-relative-urls +2ms
  hint:utils:resource-loader Searching no-vulnerable-javascript-libraries… +1ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +3ms
  hint:utils:resource-loader @hint/hint-no-vulnerable-javascript-libraries is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader no-vulnerable-javascript-libraries found in @hint/hint-no-vulnerable-javascript-libraries +123ms
  hint:utils:resource-loader Searching sri… +7ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-sri is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader sri found in @hint/hint-sri +0ms
  hint:utils:resource-loader Searching ssllabs… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-ssllabs is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader ssllabs found in @hint/hint-ssllabs +9ms
  hint:utils:resource-loader Searching strict-transport-security… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-strict-transport-security is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader strict-transport-security found in @hint/hint-strict-transport-security +0ms
  hint:utils:resource-loader Searching stylesheet-limits… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +10ms
  hint:utils:resource-loader @hint/hint-stylesheet-limits is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader stylesheet-limits found in @hint/hint-stylesheet-limits +0ms
  hint:utils:resource-loader Searching validate-set-cookie-header… +0ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +4ms
  hint:utils:resource-loader @hint/hint-validate-set-cookie-header is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader validate-set-cookie-header found in @hint/hint-validate-set-cookie-header +0ms
  hint:utils:resource-loader Searching x-content-type-options… +6ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +0ms
  hint:utils:resource-loader @hint/hint-x-content-type-options is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader x-content-type-options found in @hint/hint-x-content-type-options +10ms
  hint:utils:resource-loader Searching json… +2ms
  hint:utils:resource-loader Package hint-configuration-web-recommended not found +1ms
  hint:utils:resource-loader @hint/formatter-json is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader json found in @hint/formatter-json +23ms
  hint:utils:appinsights Sending event "analyze" to Application Insights with value {"browserslist":["and_chr 67","and_ff 60","and_qq 1.2","and_uc 11.8","android 67","android 4.4.3-4.4.4","android 4.4","baidu 7.12","chrome 68","chrome 67","chrome 66","chrome 63","chrome 49","edge 17","edge 16","firefox 61","firefox 60","firefox 52","ie 11","ie_mob 11","ios_saf 11.3-11.4","ios_saf 11.0-11.2","ios_saf 10.3","op_mini all","op_mob 46","opera 53","opera 52","safari 11.1","safari 11","samsung 7.2","samsung 6.2","samsung 4"],"formatters":["json"],"ignoredUrls":{},"hints":{"axe":"error","content-type":"error","disown-opener":"error","highest-available-document-mode":"error","html-checker":"error","http-cache":"error","http-compression":"error","meta-charset-utf-8":"error","meta-viewport":"error","no-bom":"error","no-disallowed-headers":"error","no-friendly-error-pages":"error","no-html-only-headers":"error","no-http-redirects":"error","no-protocol-relative-urls":"error","no-vulnerable-javascript-libraries":"error","sri":"error","ssllabs":"error","strict-transport-security":"error","stylesheet-limits":"error","validate-set-cookie-header":"error","x-content-type-options":"error"},"extends":["web-recommended"],"hintsTimeout":120000,"connector":{"name":"edge","options":{}}} +1s
  hint:utils:appinsights Application Insights is not enabled. +1ms
  hint:utils:appinsights Sending event "missing" to Application Insights with value ["connector-edge"] +0ms
  hint:utils:appinsights Application Insights is not enabled. +0ms
The following package is missing:
    connector-edge
There is a package from your .hintrc file not installed or with an incompatible version. Do you want us to try to install/update them? (Y/n)Y
  hint:utils:npm Running command npm install @hint/connector-edge -g +0ms
Installing packages...
npm ERR! code E404
npm ERR! 404 Not Found: @hint/connector-edge@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<redacted>\AppData\Roaming\npm-cache\_logs\2018-08-14T17_11_26_088Z-debug.log
  hint:utils:npm undefined +3s

There was a problem installing packages.
Please try executing:
    npm install @hint/connector-edge -g
            manually to install all the packages.
Exit code: 1
```

</details>

**Comment by IllusionMH** [comment]
Looks like `@hint/connector-edge` was never released publicly. It is still [private](https://github.com/webhintio/hint/blob/master/packages/connector-edge/package.json#L45) and there are nothing similar to these commits for [chome](https://github.com/webhintio/hint/commit/b6a7b76a0604c7cebc5dc4ebbf8d954b074c3ca7#diff-b442b9a919f519f32c2a0451811308ed) and [jsdom](https://github.com/webhintio/hint/commit/fd2d609ed3cfa810761ca1a880fcae8ebe15e030#diff-9f4b3e99c2d60cd97bf72c497611d7f1) connectors.

Are there any blockers that prevents `connector-edge` release?

**Comment by molant** [comment]
We need to test it and see if there are any changes with he latest version of Edge

@sarvaje is currently busy with other things for the next few days and he's the one that knows best 😩

**Comment by molant** [comment]
We will update connector-edge once the required domains are implemented in its debugging protocol. Closing for now.
