### ISSUE TITLE
jsdom connector tries to download data: uris

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1240]
Please tell us about your:

## Environment

* __`hint` version: 3.0.1
* __`Node.js` version: 8.11.3
* __`npm` version: 6.1.0

## `webhint` configuration

<details>
<summary>
`.hintrc`
</summary>

```json
{
  "extends": ["web-recommended"],
  "formatters": ["stylish"],
  "hints": {
    "axe": "off",
    "content-type": "off",
    "ssllabs": "off",
    "manifest-exists": "off",
    "x-content-type-options": "off",
    "http-cache": "warning",
    "http-compression": "warning"
  }
}
```

</details>

## URL for which `webhint` failed

* https://staging.smockle.com

## Output

<details>
<summary>webhint’s raw output</summary>

```text
https://staging.smockle.com/ downloadedUnhandled Promise rejection: { error: Error: Invalid protocol: data:
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\zone.js\dist\zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)
    at Request.init (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\request\request.js:458:31)
    at new Request (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\request\request.js:127:8)
    at request (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\request\index.js:53:10)
    at Requester._request (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\request\index.js:100:12)
    at Promise (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\@hint\utils-connector-tools\dist\src\requester.js:111:18)
    at new ZoneAwarePromise (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\zone.js\dist\zone-node.js:551:29)
    at Requester.get (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\@hint\utils-connector-tools\dist\src\requester.js:108:16)
    at JSDOMConnector._fetchUrl (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\@hint\connector-jsdom\dist\src\connector.js:35:34)
    at JSDOMConnector.fetchContent (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\@hint\connector-jsdom\dist\src\connector.js:223:21)
    at JSDOMConnector.fetchContent (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\@hint\connector-jsdom\dist\src\connector.js:221:25)
    at JSDOMConnector.resourceLoader (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\@hint\connector-jsdom\dist\src\connector.js:82:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7),
  uri: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==' } ; Zone: <root> ; Task: Request.addListener:error ; Value: { error: Error: Invalid protocol: data:
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\zone.js\dist\zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\projects\sonarwhal-rename\www.smockle.com\node_modules\hint\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)
```

</details>

**Comment by molant** [comment]
I've seen something similar with msn, the chrome connector and blobs. Maybe something related with `requester` and the hints that use it to download again assets?
