### ISSUE TITLE
No such file or directory `custom-elements.min.js`

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1365]
Steps to reproduce: 

* `npm i -g hint@3.4.7`
* `hint example.com`

```sh
$ hint example.com
- http://example.com/ downloadedUnhandled rejection promise:
    uri: undefined
    message: ENOENT: no such file or directory, open '/Users/xxxxx/.nvm/versions/node/v10.10.0/lib/node_modules/hint/node_modules/@hint/connector-jsdom/dist/src/polyfills/custom-elements.min.js'
    stack:
Error: ENOENT: no such file or directory, open '/Users/xxxxx/.nvm/versions/node/v10.10.0/lib/node_modules/hint/node_modules/@hint/connector-jsdom/dist/src/polyfills/custom-elements.min.js'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.exports.default (/Users/xxxxx/.nvm/versions/node/v10.10.0/lib/node_modules/hint/dist/src/lib/utils/fs/read-file.js:6:26)
    at Object.beforeParse (/Users/xxxxx/.nvm/versions/node/v10.10.0/lib/node_modules/hint/node_modules/@hint/connector-jsdom/dist/src/before-parse.js:11:59)
    at new JSDOM (/Users/xxxxx/.nvm/versions/node/v10.10.0/lib/node_modules/hint/node_modules/jsdom/lib/api.js:41:13)
    at Promise (/Users/xxxxx/.nvm/versions/node/v10.10.0/lib/node_modules/hint/node_modules/@hint/connector-jsdom/dist/src/connector.js:136:27)
```

---

Note: I reverted the latest releases 1 version back for now.

**Comment by alrra** [comment]
Note: I reverted the latest releases 1 version back for now.

**Comment by alrra** [comment]
Some `npm` scripts need to be updated.
