### ISSUE TITLE
OS X will not run

### ISSUE THREAD

**Issue by mituller** [webhintio/hint#1774]
I have tried a number of times to get webhint running and I run into errors on OS X. 

OS X 10.14.2
Node 10.15.0

When I run npx hint https://www.mywebsite.com I get the following:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.exports.default (/usr/local/lib/node_modules/hint/dist/src/lib/utils/fs/load-json-file.js:6:17)
    at Function.loadConfigFile (/usr/local/lib/node_modules/hint/dist/src/lib/config.js:164:54)
    at getUserConfig (/usr/local/lib/node_modules/hint/dist/src/lib/cli/analyze.js:126:47)
    at exports.default (/usr/local/lib/node_modules/hint/dist/src/lib/cli/analyze.js:191:30)
    at /usr/local/lib/node_modules/hint/dist/src/lib/cli/actions.js:7:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
A valid configuration file can't be found. Do you want to use the default configuration? To know more about the default configuration see: https://webhint.io/docs/user-guide/#default-configuration (Y/n)

```
I enter Y and get this:

   ```
┌───────────────────────────────────────────────────────────────┐
   │                                                               │
   │             Couldn't find any valid configuration             │
   │                                                               │
   │         Running hint with the default configuration.          │
   │                                                               │
   │   Learn more about how to create your own configuration at:   │
   │                                                               │
   │              https://webhint.io/docs/user-guide/              │
   │                                                               │
   └───────────────────────────────────────────────────────────────┘

{ ResourceError: Resource web-recommended not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:245:15)
    at Object.exports.loadConfiguration (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:287:20)
    at userConfig.extends.map (/usr/local/lib/node_modules/hint/dist/src/lib/config.js:41:52)
    at Array.map (<anonymous>)
    at composeConfig (/usr/local/lib/node_modules/hint/dist/src/lib/config.js:40:47)
    at Function.fromConfig (/usr/local/lib/node_modules/hint/dist/src/lib/config.js:226:28)
    at getDefaultOrCreateConfig (/usr/local/lib/node_modules/hint/dist/src/lib/cli/analyze.js:169:35)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'ResourceError', status: 'NotFound' }
```
If I try to install using:

`sudo npm install -g --engine-strict hint`

I get many errors

```
/usr/local/bin/hint -> /usr/local/lib/node_modules/hint/dist/src/bin/hint.js

> canvas@2.3.1 install /usr/local/lib/node_modules/hint/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.3.1 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hint/node_modules/canvas/build' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hint/node_modules/canvas/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/hint/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/hint/node_modules/canvas/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/hint/node_modules/canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/hint/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/hint/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/hint/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/hint/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/hint/node_modules/canvas
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/hint/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/hint/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> fsevents@1.2.7 install /usr/local/lib/node_modules/hint/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hint/node_modules/fsevents/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hint/node_modules/fsevents/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/hint/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/hint/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /usr/local/lib/node_modules/hint/node_modules/fsevents
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/hint/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/hint/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/hint/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/hint/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/hint/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/hint/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/hint/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)

> iltorb@2.4.1 install /usr/local/lib/node_modules/hint/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

WARN install EACCES: permission denied, access '/Users/mituller/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hint/node_modules/iltorb/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/hint/node_modules/iltorb
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.3.1 (node_modules/hint/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.3.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/hint/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.1 (node_modules/hint/node_modules/iltorb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.1 install: `node ./scripts/install.js || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
So, I decided to try to install locally with devDependencies and I removed the global version of webhint and installed it locally. The local install worked, but when I run it is wants to run the global version. 

`-bash: /usr/local/bin/hint: No such file or directory`

So, there seem to be many issues.

**Comment by molant** [comment]
Thanks @mituller, I'm taking a look right now.

**Comment by molant** [comment]
@mituller I can't seem to repro the issues you are having but I think I have an idea of what could be going on in some of your issues.

* `npx` issue: You might have an old version of `hint` installed globally and `npm` might be trying to use that one. We've changed how dependencies are loaded and what comes out of the box or not that might be the reason. Can you please do a `npm uninstall -g hint` followed by `npm cache clean --force` and then try again?
* `canvas@2.3.1` and `iltorb` installation issues: `canvas` is an optional dependency so even if you see errors the process should finish and you shouldn't have any problem running it. Additionally, `canvas` only has prebuilt binaries for `x64` platforms. Same goes for `iltorb` Are you running node x86 or node x64? Also please [take a look at the troubleshoot guide](https://webhint.io/docs/user-guide/troubleshoot/summary/) in case that can help as well.
* `global` vs `dependency`. To run `hint` as a dependency you will have to create a task in your `package.json` and run it via npm. I usually have something like this:

```json
{
  ...
  "scripts": {
    "hint": "hint"
  }
}
```

and then run it via `npm run hint -- https://example.com`. If you have `yarn` installed then you can do `yarn hint https://example` without `run` and `--`.

I've created the following issues with things we can improved based on your feedback. Please feel free to comment in any of those.

* https://github.com/webhintio/hint/issues/1786
* https://github.com/webhintio/hint/issues/1787

Hope this helps and please let us know if this doesn't fix your issue see if we can find a way to reproduce the problem in our machines.
