### ISSUE TITLE
Escape `\n` on `findElementLocation`

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1792]
I've run the extension in this page with the defaults and I'm getting a bunch of errors :(

```
Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': 'meta[property="og:description"][content="Pull request checklist
Make sure you:

 Signed the Contributor License Agreement
 Followed the commit message guidelines

For non-trivial changes, please make sure you also:

 Added/Updated related..."]' is not a valid selector.
    at AsyncHTMLDocument.querySelectorAll (file:///C:/Users/molant/Downloads/extension-browser-pr-1596/content-script/webhint.js:61467:51)
    at Object.exports.findElementLocation (file:///C:/Users/molant/Downloads/extension-browser-pr-1596/content-script/webhint.js:33387:50)
    at async Object.exports.findProblemLocation (file:///C:/Users/molant/Downloads/extension-browser-pr-1596/content-script/webhint.js:33446:29)
    at async CompatHTML.<anonymous> (file:///C:/Users/molant/Downloads/extension-browser-pr-1596/content-script/webhint.js:63373:30)
    at async file:///C:/Users/molant/Downloads/extension-browser-pr-1596/content-script/webhint.js:4832:40
```

This is probably not related to the extension itself.

_Originally posted by @molant in https://github.com/webhintio/hint/pull/1596#issuecomment-458726770_

**Comment by antross** [comment]
When trying to repro the issue I hit another case as well. Apparently the HTML parser allows `%` as an attribute name, but that also fails when building a selector (and when trying to use `setAttribute` for that matter).

```
hint.ts:95 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': 'meta[class="js-ga-set"][name="userId"][content="e7b44cb91a0f47c26e245ec48e6a5652"][%=""]' is not a valid selector.
    at AsyncHTMLDocument.querySelectorAll (file:///C:/Users/tross/Documents/GitHub/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:61467:51)
    at Object.exports.findElementLocation (file:///C:/Users/tross/Documents/GitHub/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:33387:50)
    at async Object.exports.findProblemLocation (file:///C:/Users/tross/Documents/GitHub/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:33446:29)
    at async CompatHTML.<anonymous> (file:///C:/Users/tross/Documents/GitHub/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:63373:30)
    at async file:///C:/Users/tross/Documents/GitHub/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:4832:40
```

**Comment by antross** [comment]
Rather than chase down each possible invalid selector, I'm going to fix the `\n` case and add a `try`/`catch` to ensure we handle potential invalid selectors gracefully. FWIW this whole code path should become obsolete after we do #1707 as we'll get location information from each element when we use `parser-html` to load the DOM snapshot.

**Comment by molant** [comment]
Sounds good to me. More reason to do #1707 sooner rather than later.
