### ISSUE TITLE
[Bug] Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by aladdin-add** [webhintio/hint#1947]
# 🐛 Bug report

## Environment

* __`hint` version:__ v4.4.0
* __`Node.js` version:__ v11.10.0
* __`OS`:__ macos
* __URL for which webhint failed: https://www.alibaba.com

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
<!-- Paste the content of your `.hintrc` here -->

```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
<!-- ✍️ Paste the raw output here -->
 repo hint https://www.alibaba.com

   ┌───────────────────────────────────────────────────────────────┐
   │                                                               │
   │             Couldn't find any valid configuration             │
   │                                                               │
   │         Running hint with the default configuration.          │
   │                                                               │
   │   Learn more about how to create your own configuration at:   │
   │                                                               │
   │              https://webhint.io/docs/user-guide/              │
   │                                                               │
   └───────────────────────────────────────────────────────────────┘

| https://marketing.aliba … %22%7D%5D&callback=__jp2 downloaded(node:19215) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
    at AsyncResourceQueue._check (/Users/weiran/.npm-global/lib/node_modules/hint/node_modules/jsdom/lib/jsdom/browser/resources/async-resource-queue.js:43:8)
    at AsyncResourceQueue.notifyItem (/Users/weiran/.npm-global/lib/node_modules/hint/node_modules/jsdom/lib/jsdom/browser/resources/async-resource-queue.js:110:14)
    at Promise.resolve.then (/Users/weiran/.npm-global/lib/node_modules/hint/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:92:31)
(node:19215) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:19215) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled rejection promise:
    uri: undefined
    message: Cannot read property 'then' of undefined
    stack:
TypeError: Cannot read property 'then' of undefined
    at AsyncResourceQueue._check (/Users/weiran/.npm-global/lib/node_modules/hint/node_modules/jsdom/lib/jsdom/browser/resources/async-resource-queue.js:43:8)
    at AsyncResourceQueue.notifyItem (/Users/weiran/.npm-global/lib/node_modules/hint/node_modules/jsdom/lib/jsdom/browser/resources/async-resource-queue.js:110:14)
    at Promise.resolve.then (/Users/weiran/.npm-global/lib/node_modules/hint/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:92:31)

```

</details>

**Comment by molant** [comment]
@sarvaje this seems related to the work you did in jsdom to load resources. Can you please take a look when you have time?

**Comment by molant** [comment]
@aladdin-add to get an analysis for the website your best option is to use the `chrome-connector`.

Can you please create a `.hintrc` file with the following content and then run `hint` again from the same folder?

```json
{
  "extends": ["web-recommended"],
  "connector": {
     "name": "chrome"
  }
}
```

Thanks!

**Comment by aladdin-add** [comment]
I've encountered a different error after upgrading to new released **v4.4.1**

```bash
➜  puck-cache git:(master) ✗ hint https://www.alibaba.com
{ ResourceError: Module hint/dist/src/lib/enums/hintscope not found when loading @hint/hint-highest-available-document-mode
    at Object.exports.tryToLoadFrom (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:141:19)
    at getResource (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:148:30)
    at sources.some (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:210:21)
    at Array.some (<anonymous>)
    at Object.exports.loadResource (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:209:13)
    at items.reduce (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:262:38)
    at Array.reduce (<anonymous>)
    at loadListOfResources (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:260:35)
    at Object.exports.loadResources (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:302:90)
    at exports.default (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/cli/analyze.js:196:36) name: 'ResourceError', status: 'DependencyError' }
➜  puck-cache git:(master) ✗ hint https://www.alibaba.com

   ┌───────────────────────────────────────────────────────────────┐
   │                                                               │
   │             Couldn't find any valid configuration             │
   │                                                               │
   │         Running hint with the default configuration.          │
   │                                                               │
   │   Learn more about how to create your own configuration at:   │
   │                                                               │
   │              https://webhint.io/docs/user-guide/              │
   │                                                               │
   └───────────────────────────────────────────────────────────────┘

{ ResourceError: Module hint/dist/src/lib/enums/hintscope not found when loading @hint/hint-highest-available-document-mode
    at Object.exports.tryToLoadFrom (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:141:19)
    at getResource (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:148:30)
    at sources.some (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:210:21)
    at Array.some (<anonymous>)
    at Object.exports.loadResource (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:209:13)
    at items.reduce (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:262:38)
    at Array.reduce (<anonymous>)
    at loadListOfResources (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:260:35)
    at Object.exports.loadResources (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:302:90)
    at exports.default (/Users/weiran/.npm-global/lib/node_modules/hint/dist/src/lib/cli/analyze.js:196:36) name: 'ResourceError', status: 'DependencyError' }
```

**Comment by molant** [comment]
We were releasing a new version of quite a few packages and the process stopped in the middle so some need to still be published. All finish the process first thing in the morning (PST).

Sorry for the inconvenience 😔

**Comment by molant** [comment]
@aladdin-add I've finished publishing all the packages and you should not encounter your last reported error any more.

**Comment by molant** [comment]
Closing this. @aladdin-add feel free to comment if you are still having issues.
