### ISSUE TITLE
[Bug] Cannot read property 'children' of undefined in browser extension [0.1]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2427]
# 🐛 Bug report

## Description

Error analyzing https://github.com/webhintio/hint/issues/1641

## Environment

* __webhint version:__ 0.0.1
* __Browser version:__ Edge 75
* __URL for which webhint failed:__ https://github.com/webhintio/hint/issues/1641

I have ZenHub, AdBlock extensions installed.

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
TypeError: Cannot read property 'children' of undefined
    at Object.t.getChildNodes (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:792919)
    at h._serializeChildNodes (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266174)
    at h._serializeElement (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266967)
    at h._serializeChildNodes (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266280)
    at h._serializeElement (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266967)
    at h._serializeChildNodes (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266280)
    at h._serializeElement (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266967)
    at h._serializeChildNodes (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266280)
    at h._serializeElement (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266967)
    at h._serializeChildNodes (file:///Users/molant/projects/@webhintio/hint/packages/extension-browser/dist/bundle/content-script/webhint.js:1:1266280)
```

</details>

**Comment by antross** [comment]
A quick investigation suggests this is due to a bug in how our DOM snapshot represents `<template>` elements that doesn't align with what the htmlparser2 tree adapter expects.

Currently we don't provide special handling for `<template>`, but apparently need to put the `DocumentFragment` representing it's `content` property as the first and only child in the `children` collection during the snapshot.
