### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by ldevernay** [webhintio/hint#3201]
# 🐛 Bug report

## Description
Audited website is : https://www.observatoire-dpe.fr/index.php/
Firefox plugin crashes totally.
Online webhint crashes too, but only on accessibility. 

## Environment

* __webhint version:__ 1.1.1 
* __Browser version:__ Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 
* __URL for which webhint failed:__ https://www.observatoire-dpe.fr/index.php/

## `webhint` configuration
Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

## Debug output
hint #1: Error in webhint analyzing this hint   
https://webhint.io/scanner/6fa660a0-2ce2-4127-aba4-674aa7945d69#hint-axe/aria-1

**Comment by antross** [comment]
Thanks for the report @ldevernay!

Digging into this a bit I see the browser extension seems to fail when trying to snapshot the DOM:
```
"TypeError: Cannot read property 'attribs' of undefined
    at snapshot (<anonymous>:131:32)
    at https://www.observatoire-dpe.fr/js/prototype-1.6.0.2.js:635:20
    at https://www.observatoire-dpe.fr/js/prototype-1.6.0.2.js:595:9
    at Array.forEach (<anonymous>)
    at Array.each (https://www.observatoire-dpe.fr/js/prototype-1.6.0.2.js:594:12)
    at Array.collect (https://www.observatoire-dpe.fr/js/prototype-1.6.0.2.js:634:10)
    at snapshot (<anonymous>:129:45)
    at https://www.observatoire-dpe.fr/js/prototype-1.6.0.2.js:635:20
    at https://www.observatoire-dpe.fr/js/prototype-1.6.0.2.js:595:9
    at Array.forEach (<anonymous>)"
```

Given the library in the callstack I'm suspecting both webhint's browser extension DOM snapshot utility and `axe-core` (which powers webhint's accessibility checks) are being affected by overrides to native APIs in the page.

**Comment by molant** [comment]
Seems that #3262 might be related to this as well.
