### ISSUE TITLE
[Bug] The built-in configuration does not run

### ISSUE THREAD

**Issue by jm-trd-ms** [webhintio/hint#3970]
# 🐛 Bug report

## Description

1.  Open zsh shell.  
1.  Run `npx hint https://www.example.com`

## Environment

* __`hint` version:__ zsh: command not found: hint  
* __`Node.js` version:__ v14.7.0. 
* __`OS`:__ macOS Catalina 10.15.6  
* __URL for which webhint failed:__ https://www.example.com  

## `webhint` configuration

<details>
<summary>webhint configuration</summary>

```js
Using the built-in configuration.  
Visit https://webhint.io/docs/user-guide/ to learn how to create your own configuration.  
```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint raw output</summary>

```text
v-jomar7@Edge-Dev-Docs-MacBook-Pro / % npx hint https://example.com
Using the built-in configuration.
Visit https://webhint.io/docs/user-guide/ to learn how to create your own configuration.
✖
Error: No installation found for: ""
    at Object.exports.getInstallationPath (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/node_modules/@hint/connector-puppeteer/dist/src/lib/chromium-finder.js:247:15)
    at PuppeteerConnector.toPuppeteerOptions (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/node_modules/@hint/connector-puppeteer/dist/src/connector.js:55:35)
    at new PuppeteerConnector (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/node_modules/@hint/connector-puppeteer/dist/src/connector.js:37:30)
    at new Engine (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/dist/src/lib/engine.js:34:26)
    at Analyzer.analyze (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/dist/src/lib/analyzer.js:141:27)
    at exports.default (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/dist/src/lib/cli/analyze.js:317:23)
    at async /Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/dist/src/lib/cli/actions.js:8:20
    at async Object.exports.execute (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/dist/src/lib/cli.js:38:23)
    at async run (/Users/v-jomar7/.npm/_npx/66878/lib/node_modules/hint/dist/src/bin/hint.js:44:24)
v-jomar7@Edge-Dev-Docs-MacBook-Pro / %
```

</details>

**Comment by antross** [comment]
Thanks @jm-trd-ms! 

This seems really similar to https://github.com/webhintio/hint/issues/3900 which should have been fixed already...

Just to double-check: you do have a Chromium-based browser installed on your machine already, correct?

**Comment by jm-trd-ms** [comment]
I have Microsoft Edge (Chromium) installed, but the issue is on in the zsh command-line (the default macOS terminal shell).

**Comment by molant** [comment]
Hello @deadlyhifi ,
Thanks for doing this research!

> Add '/Contents/MacOS/Microsoft Edge to the Edge browser array on line 58.

SGTM, you should probably update [the comment in L41 as well](https://github.com/webhintio/hint/blob/0f057d6c3992d66385310ea2238234b865047dc7/packages/connector-puppeteer/src/lib/chromium-finder.ts#L41)

> Edit the error message on line 27 to be more descriptive.

I believe the problem real problem is in [line 405](https://github.com/webhintio/hint/blob/0f057d6c3992d66385310ea2238234b865047dc7/packages/connector-puppeteer/src/lib/chromium-finder.ts#L405). That message should have the right data if a particular browser is passed in the configuration. Because it is not specified then the value is empty.
I can think of a couple options but feel free to suggest others:

* Update the value of `browserFound` right before throwing to something like "Any supported browser."
* Create a new error message more explicit and use it instead of `ERRORS.NoInstallationFound`

> Add Brave to the list. Then does Opera and every other Chromium browser need adding?

Yes, each browser has a different path so they need to be added manually

> A notice on the getting started guide.

Maybe add it to https://webhint.io/docs/user-guide/troubleshoot/summary/ as well?
