### ISSUE TITLE
[Bug] A installation bug? 

### ISSUE THREAD

**Issue by hustnzj** [webhintio/hint#4737]
# 🐞 Bug report

## Description

When I run webhint, I come across the problem: `Error: Cannot find module '@hint/utils-dom'` which shouldn't occur per its official docs. I manually install the missing package, and it works now. But I want to know what caused this error. 

## Details

A linter well-worth looking at is [webhint][1]

I have followed the steps to [use webhint in your project][2]: 
1. install the devDependency: `npm i -D hint`, the result as below:
    ```zsh
     ~/Desktop/temp/webhint  npm i -D hint              
    npm WARN deprecated har-validator@5.1.5: this
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    
    added 350 packages in 20s
    
    1 package is looking for funding
      run `npm fund` for details
    ```

2. add the script task to `package.json` file:
    ```
    {
        ...
        "scripts": {
            "webhint": "hint http://localhost:8080"
        }
    }
    ```
3. start webhint: `npm run webhint`

But the errors are always generated as below:

```zsh
 ~/Desktop/temp/webhint  npm run webhint

> webhint@1.0.0 webhint
> hint http://localhost:8080

Error: Cannot find module '@hint/utils-dom'
Require stack:
- /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/hint-context.js
- /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/engine.js
- /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/index.js
- /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/analyze.js
- /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/actions.js
- /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli.js
- /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/bin/hint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module.patchedRequire [as require] (/Users/hustnzj/Desktop/temp/webhint/node_modules/diagnostic-channel/dist/src/patchRequire.js:15:46)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/hint-context.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/hint-context.js',
    '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/engine.js',
    '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/index.js',
    '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/analyze.js',
    '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/actions.js',
    '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli.js',
    '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/bin/hint.js'
  ]
}
```
I'm sure that there is no module `@hint/utils-dom` under the `node_modules/@hint` directory and I don't know how to trace this kind of problem for now. 
![image](https://user-images.githubusercontent.com/27875723/135074100-4e0b027a-4396-4502-9856-25a0ca2d9437.png)

So I have to install it manually: `npm i @hint/utils-dom -D` and rerun `npm run webhint`.  Surprisingly, it works!  
```zsh
 ~/Desktop/temp/webhint  npm run webhint         

> y@1.0.0 webhint
> hint http://localhost:8080

Using the built-in configuration.
Visit https://webhint.io/docs/user-guide/ to learn how to create your own configuration.
✖ Analyzing http://localhost:8080/
AnalyzerError: net::ERR_CONNECTION_REFUSED at http://localhost:8080/
    at Analyzer.analyze (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/analyzer.js:151:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async exports.default (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/analyze.js:317:9)
    at async /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/actions.js:8:20
    at async Object.execute (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli.js:38:23)
    at async run (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/bin/hint.js:44:24) {
  status: 'AnalyzeError'
}
```

Although it failed again, the reason is that my local server doesn't listen to port 8080.

After changing the script a little bit, the result is reasonable.
```zsh
~/Desktop/temp/webhint  npm run webhint

> y@1.0.0 webhint
> hint https://webhint.io

Using the built-in configuration.
Visit https://webhint.io/docs/user-guide/ to learn how to create your own configuration.
✖ Finishing...You can view the HTML report in "/Users/hustnzj/Desktop/temp/webhint/hint-report/https-webhint-io.html"
compat-api/html            2 warnings
compat-api/css             3 warnings
content-type               9 warnings
no-bom                     10 errors
disown-opener              11 warnings
strict-transport-security  18 errors
x-content-type-options     18 errors
no-disallowed-headers      36 warnings
http-cache                 37 warnings  4 hints
http-compression           48 errors    4 warnings            4 hints
✖ Found a total of 94 errors, 102 warnings, 8 hints and 0 informations
```

Now the missing package along with a bunch of others were all installed:
![image](https://user-images.githubusercontent.com/27875723/135075045-4d621246-6a9e-44a9-8562-f0fbf845ac53.png)

According to the [readme][3] of `@hint/utils-dom` package which is installed automatically when adding webhint to your project so running the following is enough:
```zsh
npm install hint --save-dev
```

To prove the weird phenomenon is not caused by the network, I tried three times, created three different projects, and did all the same steps as above. 
![image](https://user-images.githubusercontent.com/27875723/135082711-ca9a0483-ccd9-443f-8dbb-10dff2399937.png)

**So Why do I have to install the `@hint/utils-dom` manually?**

[1]: https://webhint.io/
[2]: https://webhint.io/docs/user-guide/#use-webhint-in-your-project
[3]: https://www.npmjs.com/package/@hint/utils-dom

## The related information
`webhint` version: v6.1.4
`OS`: macOS Big Sur Version 11.2.3
using the default `.hintrc` file.
`node.js`: v14.17.6
`npm`: 7.23.0

**Comment by asdfchj6** [comment]
> # 🐞 Bug report
> 
> ## Description
> 
> When I run webhint, I come across the problem: `Error: Cannot find module '@hint/utils-dom'` which shouldn't occur per its official docs. I manually install the missing package, and it works now. But I want to know what caused this error. 
> 
> ## Details
> 
> A linter well-worth looking at is [webhint][1]
> 
> I have followed the steps to [use webhint in your project][2]: 
> 1. install the devDependency: `npm i -D hint`, the result as below:
>     ```zsh
>      ~/Desktop/temp/webhint  npm i -D hint              
>     npm WARN deprecated har-validator@5.1.5: this
>     npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
>     
>     added 350 packages in 20s
>     
>     1 package is looking for funding
>       run `npm fund` for details
>     ```
> 
> 2. add the script task to `package.json` file:
>     ```
>     {
>         ...
>         "scripts": {
>             "webhint": "hint http://localhost:8080"
>         }
>     }
>     ```
> 3. start webhint: `npm run webhint`
> 
> But the errors are always generated as below:
> 
> ```zsh
>  ~/Desktop/temp/webhint  npm run webhint
> 
> > webhint@1.0.0 webhint
> > hint http://localhost:8080
> 
> Error: Cannot find module '@hint/utils-dom'
> Require stack:
> - /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/hint-context.js
> - /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/engine.js
> - /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/index.js
> - /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/analyze.js
> - /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/actions.js
> - /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli.js
> - /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/bin/hint.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at Module.patchedRequire [as require] (/Users/hustnzj/Desktop/temp/webhint/node_modules/diagnostic-channel/dist/src/patchRequire.js:15:46)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Object.<anonymous> (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/hint-context.js:6:21)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/hint-context.js',
>     '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/engine.js',
>     '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/index.js',
>     '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/analyze.js',
>     '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/actions.js',
>     '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli.js',
>     '/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/bin/hint.js'
>   ]
> }
> ```
> I'm sure that there is no module `@hint/utils-dom` under the `node_modules/@hint` directory and I don't know how to trace this kind of problem for now. 
> ![image](https://user-images.githubusercontent.com/27875723/135074100-4e0b027a-4396-4502-9856-25a0ca2d9437.png)
> 
> So I have to install it manually: `npm i @hint/utils-dom -D` and rerun `npm run webhint`.  Surprisingly, it works!  
> ```zsh
>  ~/Desktop/temp/webhint  npm run webhint         
> 
> > y@1.0.0 webhint
> > hint http://localhost:8080
> 
> Using the built-in configuration.
> Visit https://webhint.io/docs/user-guide/ to learn how to create your own configuration.
> ✖ Analyzing http://localhost:8080/
> AnalyzerError: net::ERR_CONNECTION_REFUSED at http://localhost:8080/
>     at Analyzer.analyze (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/analyzer.js:151:23)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async exports.default (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/analyze.js:317:9)
>     at async /Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli/actions.js:8:20
>     at async Object.execute (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/lib/cli.js:38:23)
>     at async run (/Users/hustnzj/Desktop/temp/webhint/node_modules/hint/dist/src/bin/hint.js:44:24) {
>   status: 'AnalyzeError'
> }
> ```
> 
> Although it failed again, the reason is that my local server doesn't listen to port 8080.
> 
> After changing the script a little bit, the result is reasonable.
> ```zsh
> ~/Desktop/temp/webhint  npm run webhint
> 
> > y@1.0.0 webhint
> > hint https://webhint.io
> 
> Using the built-in configuration.
> Visit https://webhint.io/docs/user-guide/ to learn how to create your own configuration.
> ✖ Finishing...You can view the HTML report in "/Users/hustnzj/Desktop/temp/webhint/hint-report/https-webhint-io.html"
> compat-api/html            2 warnings
> compat-api/css             3 warnings
> content-type               9 warnings
> no-bom                     10 errors
> disown-opener              11 warnings
> strict-transport-security  18 errors
> x-content-type-options     18 errors
> no-disallowed-headers      36 warnings
> http-cache                 37 warnings  4 hints
> http-compression           48 errors    4 warnings            4 hints
> ✖ Found a total of 94 errors, 102 warnings, 8 hints and 0 informations
> ```
> 
> Now the missing package along with a bunch of others were all installed:
> ![image](https://user-images.githubusercontent.com/27875723/135075045-4d621246-6a9e-44a9-8562-f0fbf845ac53.png)
> 
> According to the [readme][3] of `@hint/utils-dom` package which is installed automatically when adding webhint to your project so running the following is enough:
> ```zsh
> npm install hint --save-dev
> ```
> 
> To prove the weird phenomenon is not caused by the network, I tried three times, created three different projects, and did all the same steps as above. 
> ![image](https://user-images.githubusercontent.com/27875723/135082711-ca9a0483-ccd9-443f-8dbb-10dff2399937.png)
> 
> 
> **So Why do I have to install the `@hint/utils-dom` manually?**
> 
> 
> [1]: https://webhint.io/
> [2]: https://webhint.io/docs/user-guide/#use-webhint-in-your-project
> [3]: https://www.npmjs.com/package/@hint/utils-dom
> 
> 
> ## The related information
> `webhint` version: v6.1.4
> `OS`: macOS Big Sur Version 11.2.3
> using the default `.hintrc` file.
> `node.js`: v14.17.6
> `npm`: 7.23.0

**Comment by n0wak** [comment]
I am running into the same issue just running 'npx hint https://webhint.io' from commandline with npm 8.8.0. This is on an M1 mac running os 12.3

**Comment by mohd-akram** [comment]
I encountered this issue as well. The solution was to remove the webhint directory in VS Code's global storage to let it install again: `rm -r ~/Library/Application\ Support/Code/User/globalStorage/webhint.vscode-webhint`
