### ISSUE TITLE
[Bug] verbose stack Error: could not determine executable to run

### ISSUE THREAD

**Issue by fmanimashaun** [webhintio/hint#5349]
# 🐞 Bug report

## Description

Running to error while trying to run `npx hint .` after installation. I have used this before now in previous projects and I have no issues, but now, I did the same thing and I am having issues.

## Details

Below is the log:
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\fisay\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.19.2
2 info using node@v16.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\fisay\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 5ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\Microverse\Awesome_books\.npmrc Completed in 1ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:C:\Users\fisay\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\fisay\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 19ms
19 timing npm:load:configload Completed in 19ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm exec hint .
23 verbose argv "exec" "--" "hint" "."
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 5ms
26 timing npm:load:display Completed in 7ms
27 verbose logfile logs-max:10 dir:C:\Users\fisay\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\fisay\AppData\Local\npm-cache\_logs\2022-10-31T17_11_28_385Z-debug-0.log
29 timing npm:load:logFile Completed in 56ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 89ms
33 silly logfile start cleaning logs, removing 2 files
34 timing arborist:ctor Completed in 1ms
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing command:exec Completed in 77ms
38 verbose stack Error: could not determine executable to run
38 verbose stack     at getBinFromManifest (C:\Users\fisay\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
38 verbose stack     at exec (C:\Users\fisay\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:173:15)
38 verbose stack     at async module.exports (C:\Users\fisay\AppData\Roaming\npm\node_modules\npm\lib\cli.js:78:5)
39 verbose pkgid hint@2.0.0
40 verbose cwd D:\Microverse\Awesome_books
41 verbose Windows_NT 10.0.22000
42 verbose node v16.16.0
43 verbose npm  v8.19.2
44 error could not determine executable to run
45 verbose exit 1
46 timing npm Completed in 454ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     C:\Users\fisay\AppData\Local\npm-cache\_logs\2022-10-31T17_11_28_385Z-debug-0.log
```

**Comment by vidorteg** [comment]
Hi @fmanimashaun 

thanks for reporting the issue, but seems we will need more information:
- what is the OS used?
- can you try running `npx hint http://example.com`, what is the output?
- can you post your configuration (if any)?
